version: "3.7"
services:
  api_service:
    build: .
    restart: on-failure
    env_file: system_vars.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    depends_on:
      - mysql_db

  mysql_db:
    image: "mysql:latest"
    restart: always
    env_file: system_vars.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    